apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: ciond-project5-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ciond-project5-service
  template:
    metadata:
      labels:
        app: ciond-project5-service
    spec:
      containers:
      - name: web
        image: 944095567375.dkr.ecr.us-east-1.amazonaws.com/ciond_project5:latest
        ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: serviceloadbalance
spec:
  selector:
    app: ciond-project5-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80